name: Build and test

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 6.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Install dependencies for tests
        run: dotnet restore
      - name: Build test
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal